In [1]:
import numpy as np

In [2]:
np.zeros((2,3)), np.ones((3,4))

(array([[0., 0., 0.],
        [0., 0., 0.]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [3]:
A=np.random.rand(8,8)

In [4]:
a=np.random.rand(10)
b=np.random.randint(5, size=10)*100
c=np.random.randn(10)

In [5]:
np.vstack((a,b,c))

array([[ 5.67661408e-01,  3.10269498e-01,  2.84559884e-02,
         4.36020931e-01,  6.41390334e-01,  4.84518680e-01,
         8.36743619e-01,  4.59834573e-01,  5.18130279e-01,
         5.81591758e-01],
       [ 1.00000000e+02,  2.00000000e+02,  0.00000000e+00,
         3.00000000e+02,  3.00000000e+02,  4.00000000e+02,
         3.00000000e+02,  1.00000000e+02,  4.00000000e+02,
         4.00000000e+02],
       [ 5.09415985e-01, -1.38892087e+00, -4.68339371e-01,
        -2.32741133e-01, -1.37179413e+00, -8.01632037e-02,
        -3.82723080e-02, -4.46196615e-01,  1.21437060e+00,
         1.78136763e+00]])

In [6]:
X=np.column_stack((a,b,c))

In [7]:
X

array([[ 5.67661408e-01,  1.00000000e+02,  5.09415985e-01],
       [ 3.10269498e-01,  2.00000000e+02, -1.38892087e+00],
       [ 2.84559884e-02,  0.00000000e+00, -4.68339371e-01],
       [ 4.36020931e-01,  3.00000000e+02, -2.32741133e-01],
       [ 6.41390334e-01,  3.00000000e+02, -1.37179413e+00],
       [ 4.84518680e-01,  4.00000000e+02, -8.01632037e-02],
       [ 8.36743619e-01,  3.00000000e+02, -3.82723080e-02],
       [ 4.59834573e-01,  1.00000000e+02, -4.46196615e-01],
       [ 5.18130279e-01,  4.00000000e+02,  1.21437060e+00],
       [ 5.81591758e-01,  4.00000000e+02,  1.78136763e+00]])

In [8]:
X[1:2,1:]

array([[200.        ,  -1.38892087]])

In [9]:
X[:5, 1:]

array([[ 1.00000000e+02,  5.09415985e-01],
       [ 2.00000000e+02, -1.38892087e+00],
       [ 0.00000000e+00, -4.68339371e-01],
       [ 3.00000000e+02, -2.32741133e-01],
       [ 3.00000000e+02, -1.37179413e+00]])

# LIST

In [10]:
lst=[]

In [11]:
lst.append('abc')

In [12]:
lst

['abc']

In [13]:
lst.insert(0,'def')

In [14]:
lst

['def', 'abc']

In [15]:
lst.insert(-1,'last-1')

In [16]:
lst

['def', 'last-1', 'abc']

In [17]:
lst.pop(0)

'def'

In [18]:
lst

['last-1', 'abc']

In [19]:
del lst[1]

In [20]:
lst

['last-1']

In [21]:
lsts=lst+ [str(i) for i in [1,2,3,4,5]]

In [22]:
lsts

['last-1', '1', '2', '3', '4', '5']

In [23]:
lsts[::-1]

['5', '4', '3', '2', '1', 'last-1']

In [24]:
lsts.sort()

In [25]:
lsts.index('1')

0

In [26]:
lsts

['1', '2', '3', '4', '5', 'last-1']

In [27]:
for i in reversed(lsts):
    print(i)

last-1
5
4
3
2
1


In [28]:
np.random.choice(lsts,10)

array(['1', '4', '4', '3', '4', '1', '5', '3', '3', '2'], dtype='<U6')

In [29]:
s='You Know When  THAT  Hotline Bling'

In [30]:
s.split()[::-1]

['Bling', 'Hotline', 'THAT', 'When', 'Know', 'You']

In [31]:
result=[]
for i in s.split(' ')[::-1]:
    new_s=[]
    for j in i:
        if j.isupper():
            new_s.append(j.lower())
        elif j.islower():
            new_s.append(j.upper())
        else:
            new_s.append(' ')
    result.append(''.join(new_s))
' '.join(result)    

'bLING hOTLINE  that  wHEN kNOW yOU'

In [32]:
result

['bLING', 'hOTLINE', '', 'that', '', 'wHEN', 'kNOW', 'yOU']

In [33]:
' '.join(s.swapcase().split(' ')[::-1])

'bLING hOTLINE  that  wHEN kNOW yOU'

In [34]:
n=12

In [35]:
n!=1 and sum([n%i==0 for i in list(range(2,n+1))])==1

False

In [36]:
a=range(2,n+1)

In [37]:
[i for i in a if n%i!=0]

[5, 7, 8, 9, 10, 11]

In [38]:
x=3
y=36

In [39]:
def lcm(x,y):
    if x>=y:
        lcm=y
    else:
        lcm=x
    
    while True:
        if (lcm%x==0) and (lcm%y==0):
            break
        lcm+=1
    return lcm
    
        
        

In [40]:
lcm(x,y)

36

In [41]:
x*y/lcm(x,y)

3.0

In [42]:
def gcd(x,y):
    while y:
        x, y = y, x%y
    return x

In [43]:
gcd(x,y)

3

In [44]:
x*y/gcd(x,y)

36.0

In [45]:
x*y/lcm(x,y)

3.0

In [46]:
n=12
while n:
    print(n)
    n-=1

12
11
10
9
8
7
6
5
4
3
2
1
