In [1]:
import numpy as np

In [55]:
np.zeros((2,3)), np.ones((3,4))

(array([[0., 0., 0.],
        [0., 0., 0.]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [19]:
A=np.random.rand(8,8)

In [40]:
a=np.random.rand(10)
b=np.random.randint(5, size=10)*100
c=np.random.randn(10)

In [41]:
np.vstack((a,b,c))

array([[ 5.40208116e-01,  7.79656369e-01,  9.36994270e-01,
         7.97284862e-01,  2.24188056e-01,  8.68636711e-01,
         4.06738850e-02,  2.88823121e-01,  3.96271386e-01,
         8.96392457e-01],
       [ 3.00000000e+02,  3.00000000e+02,  1.00000000e+02,
         0.00000000e+00,  3.00000000e+02,  4.00000000e+02,
         4.00000000e+02,  0.00000000e+00,  2.00000000e+02,
         1.00000000e+02],
       [-2.05707810e+00,  5.14216720e-01,  7.27313228e-02,
         7.78074231e-01, -1.42820859e-01, -8.95225909e-01,
         3.26033637e-01,  1.52533139e+00,  5.15508431e-01,
        -4.74755873e-01]])

In [42]:
X=np.column_stack((a,b,c))

In [43]:
X

array([[ 5.40208116e-01,  3.00000000e+02, -2.05707810e+00],
       [ 7.79656369e-01,  3.00000000e+02,  5.14216720e-01],
       [ 9.36994270e-01,  1.00000000e+02,  7.27313228e-02],
       [ 7.97284862e-01,  0.00000000e+00,  7.78074231e-01],
       [ 2.24188056e-01,  3.00000000e+02, -1.42820859e-01],
       [ 8.68636711e-01,  4.00000000e+02, -8.95225909e-01],
       [ 4.06738850e-02,  4.00000000e+02,  3.26033637e-01],
       [ 2.88823121e-01,  0.00000000e+00,  1.52533139e+00],
       [ 3.96271386e-01,  2.00000000e+02,  5.15508431e-01],
       [ 8.96392457e-01,  1.00000000e+02, -4.74755873e-01]])

In [50]:
X[1:2,1:]

array([[300.        ,   0.51421672]])

In [54]:
X[:5, 1:]

array([[ 3.00000000e+02, -2.05707810e+00],
       [ 3.00000000e+02,  5.14216720e-01],
       [ 1.00000000e+02,  7.27313228e-02],
       [ 0.00000000e+00,  7.78074231e-01],
       [ 3.00000000e+02, -1.42820859e-01]])